title: Skill Issue
description: "Welcome to my awesome blog about technology and programming!"
theme: minima
skin: auto

# Site settings
author:
  name: Nikhil Naidu

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Category settings
show_excerpts: true
categories_path: /categories/
tag_path: /tags/

# Collections
collections:
  category:
    output: true
    permalink: /category/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: category

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-category
    tag: archive-tag
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
